config/routes.rb
Rails.application.routes.draw do

root to: "blogposts#index"
  devise_for :users, :controllers => { registrations: "registrations" }
  
      resources :users do
        resources :blogposts
    end
  
  
  
  

end

app/models/blogpost.rb
class Blogpost < ActiveRecord::Base

    belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
 
     has_many :blogposts
 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController

before_action :authenticate_user!

	def index
	   #@user = User.find(params[:user_id])
	    @user = current_user
		@blogposts = User.find(@user.id).blogposts
		render "index"
	end
	
	
	def new
	    @user = current_user
		#@user = User.find(params[:user_id])
		@blogpost = Blogpost.new
	end
	
	
	def show
        @user = current_user
        @post = User.find(current_user).blogposts.find(params[:id])
        #@user = User.find(params[:user_id])	   
	    #@post = User.find(params[:user_id]).blogposts.find(params[:id])
	    render "post"
	end
	
	
	def create
	    User.find(current_user).blogposts.create(blogpost_params)
	#	User.find(params[:user_id]).blogposts.create(blogpost_params)
		redirect_to user_blogposts_path
	end
	
	
	def blogpost_params
		params.require(:blogpost).permit(:blog_post, :blog_title, :user_id)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

private

    def sign_up_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :username, :about_me)
    end

    def account_update_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :username, :about_me)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
    @users = User.all
    @user = User.new
    
    render "index" 
end



    def create
         user = User.new(user_params)
    
    # User.create(
    #  firstname: params[:user][:firstname],
     # lastname: params[:user][:lastname],
      #username:  params[:user][:username], 
      # role: params[:user][:role]
        #)
        user.save
        
        if user.valid? 
            redirect_to "/users"
        else
            flash[:error] = "Form validation failed" 
            redirect_to "/users"
        end
    end


def edit 
        @user = User.find(params[:id])
    end


def update
    user = User.find(params[:id])
    user.update_attributes(user_params)
    redirect_to "/users"
end
    
def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to "/users"
end


private
    def user_params
        params.require(:user).permit(:firstname, :lastname, :username, :role)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/TemplateFiles/login.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Login to Blog.Ly</title>

	<!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />

    <link href="css/style.css" rel="stylesheet">
</head>
<body>

<div class="small-container well">
	<h2>Login</h2>

	<div class="margin-top-20">
		<input type="email" class="form-control" placeholder="Email Address" />
	</div>

	<div class="margin-top-20">
		<input type="password" class="form-control" placeholder="Password" />
	</div>

	<div class="margin-top-20">
		<button type="submit" class="btn btn-primary">Login</button>
	</div>

	<div class="margin-top-10">
		<a href="#">Create an account</a>
	</div>
</div>

</body>
</html>

app/views/TemplateFiles/signup.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Create Account on Blog.Ly</title>

	<!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />

    <link href="css/style.css" rel="stylesheet">
</head>
<body>

<div class="small-container well">
	<h2>Create Account</h2>

	<div class="margin-top-20">
		<input type="text" class="form-control" placeholder="First Name" />
	</div>

	<div class="margin-top-20">
		<input type="text" class="form-control" placeholder="Last Name" />
	</div>

	<div class="margin-top-20">
		<input type="email" class="form-control" placeholder="Email Address" />
	</div>

	<div class="margin-top-20">
		<input type="password" class="form-control" placeholder="Password" />
	</div>

	<div class="margin-top-20">
		<input type="password" class="form-control" placeholder="Password Confirm" />
	</div>

	<div class="margin-top-20">
		<input type="text" class="form-control" placeholder="Username" />
	</div>

	<div class="margin-top-20">
		<textarea class="form-control" placeholder="About Me"></textarea>
	</div>

	<div class="margin-top-20">
		<button type="submit" class="btn btn-primary">Create Account</button>
	</div>

	<div class="margin-top-10">
		<a href="#">Already have an account? Log in</a>
	</div>
</div>

</body>
</html>

app/views/blogposts/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">

    <title>My Blog</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />

    <!-- Custom CSS -->
    <link href="css/style.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Blog.Ly</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <%= current_user.email %> <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="<%= new_user_blogpost_path(@user.id) %>">New Post</a></li>
                            <li role="separator" class="divider"></li>
                            
                            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
                        
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>


    <!-- Page Content -->
    <div class="container">

        <!-- Page Heading -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header"> <%= current_user.first_name %>&nbsp;<%= current_user.last_name %>
                    <small><%= current_user.email %></small>
                </h1>
            </div>
        </div>
        <!-- /.row -->
        
        
      




        <hr>

        <!-- Post Two -->
        
        
        
        <% @blogposts.each do |post| %> 
        
        
        <div class="row">
            <div class="col-md-7">
                <a href="#">
                    <img class="img-responsive" src="http://placehold.it/700x300" alt="">
                </a>
            </div>
            <div class="col-md-5">
                <h3><%= post.blog_title %></h3>
                
                
                
                <p><%= post.blog_post  %></p>
                
                
                <a class="btn btn-primary" href="/users/<%= post.user_id %>/blogposts/<%= post.id %>">View Post <span class="glyphicon glyphicon-chevron-right"></span></a>
            </div>
        </div>
         <hr>
        <% end %> 
        <!-- /.row -->



        <hr>

        <!-- Pagination -->
        <div class="text-center">
            Pagination Here
        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy;<%= current_user.first_name %>&nbsp;<%= current_user.last_name %> 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>

</html>

app/views/blogposts/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">

    <title>New Post</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />

    <link href="css/style.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Blog.Ly</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %>&nbsp;<%= current_user.last_name %><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">New Post</a></li>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->


	<%= form_for [@user, @blogpost] do |f| %>


                <!-- Title -->
                <h1>New Post</h1>



                		<%= f.text_field :blog_title, :value => "Title", class:"form-control" %>
                		<br>&nbsp;<br>
                		<%= f.text_area :blog_post, rows: 10, class:"form-control" %>


                <div class="margin-top-20">
                    <input type="text" class="form-control" placeholder="Blog Image" />
                </div>

                <div class="margin-top-20">
                    <button type="submit" class="btn btn-primary">Submit Post</button>
                </div>
	<% end %>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Post Tips</h4>
                    <p>Happy posting.</p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; <%= current_user.first_name %>&nbsp;<%= current_user.last_name %> 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>

</html>

app/views/blogposts/post.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">

    <title>My Post</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" />

    <link href="css/style.css" rel="stylesheet">

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Blog.Ly</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.first_name %>&nbsp;<%= current_user.last_name %><span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">New Post</a></li>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <!-- Blog Post Content Column -->
            <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                <h1><%= @post.blog_title %></h1>

                <!-- Author -->
                <p class="lead">
                    by <%= current_user.first_name %>&nbsp;<%= current_user.last_name %> 
                </p>

                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> <%= @post.created_at %></p>

                <hr>

                <!-- Preview Image -->
                <img class="img-responsive" src="http://placehold.it/900x300" alt="">

                <hr>

                <!-- Post Content -->
                
                <%= @post.blog_post %> 
                
                <hr>

                <!-- Blog Comments -->

                <!-- Comments Form -->
                <div class="well">
                    <h4>Leave a Comment:</h4>
                    <form role="form">
                        <div class="form-group">
                            <textarea class="form-control" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit Comment</button>
                    </form>
                </div>

                <hr>

                <!-- Posted Comments -->

                <!-- Comment -->
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

                <!-- Comment -->
                <div class="media">
                    <div class="media-body">
                        <h4 class="media-heading">Start Bootstrap
                            <small>August 25, 2014</small>
                        </h4>
                        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                    </div>
                </div>

            </div>

            <!-- Blog Sidebar Widgets Column -->
            <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>About the Author</h4>
                    <p><%= @user.about_me %></p>
                </div>

            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; <%= current_user.first_name %>&nbsp;<%= current_user.last_name %> 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>